apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "otus-msa-hw3.fullname" . }}-monitor"
  labels:
    {{- include "otus-msa-hw3.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      scheme: http
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      {{- include "otus-msa-hw3.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"